# Workflow untuk mendeploy konten statis ke GitHub Pages menggunakan Vite dan pnpm
name: Deploy konten statis ke Pages

on:
  # Berjalan pada push yang menargetkan branch default
  push:
    branches: ['main']

  # Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions
  workflow_dispatch:

# Mengatur izin GITHUB_TOKEN untuk memungkinkan deployment ke GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Mengizinkan satu deployment bersamaan
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Job tunggal untuk build dan deploy
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Instal pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Gunakan Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Sesuaikan dengan versi Node.js yang Anda gunakan
        cache: 'pnpm'
    - name: Instal dependensi
      run: pnpm install
    - name: Build dengan Vite
      run: pnpm run build
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'  # Sesuaikan dengan output directory Vite Anda
    - name: Deploy ke GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
